# Generated by Django 2.2.10 on 2020-04-03 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('movies', '0002_auto_20200403_0202'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('celebs', '0002_auto_20200403_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='added_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_moviecomment_adders', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='moviecomment',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_moviecomment_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='moviecomment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.Movie', verbose_name='Movie'),
        ),
        migrations.AddField(
            model_name='celebcomment',
            name='added_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_celebcomment_adders', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='celebcomment',
            name='celeb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='celebs.Celebrity', verbose_name='Celebrity'),
        ),
        migrations.AddField(
            model_name='celebcomment',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_celebcomment_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
    ]
