# Generated by Django 2.2.10 on 2020-04-03 02:02

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Added Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Added Date')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='Slug')),
                ('content', models.CharField(blank=True, default='', max_length=250, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Added Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Added Date')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='Slug')),
                ('release_year', models.CharField(max_length=4, verbose_name='Release Year')),
                ('duration', models.SmallIntegerField(blank=True, default=0, help_text='in minutes', verbose_name='Duration')),
                ('imdb_rating', models.FloatField(blank=True, default=0, help_text='e.g. 6.8', verbose_name='IMDB Rating')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('source_content', models.URLField(blank=True, default='', verbose_name='Content Source')),
                ('trailer', models.URLField(blank=True, default='', help_text='trailer url (ONLY for youtube videos yet)', verbose_name='Trailer')),
                ('image', models.ImageField(blank=True, default='movies/default-movie.jpg', null=True, upload_to=movies.models.movie_directory_path, verbose_name='Image')),
                ('credit_image', models.CharField(blank=True, default='', max_length=250, verbose_name='Image Credit')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ('-release_year', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', help_text='e.g. short story, screenplay for writer or voice for cast', max_length=75, verbose_name='Role')),
                ('screen_name', models.CharField(blank=True, default='', help_text="Crew's name on movie", max_length=75, verbose_name='Screen Name')),
            ],
        ),
        migrations.CreateModel(
            name='PgRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Added Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Added Date')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='Slug')),
                ('code', models.CharField(max_length=5, verbose_name='Code')),
                ('content', models.CharField(blank=True, default='', max_length=250, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'PG Rating',
                'verbose_name_plural': 'PG Ratings',
                'ordering': ('pk',),
            },
        ),
    ]
